version: "3.1"

services:
  PostgreSQL:
#   restart: always
    container_name: postgres_9
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      #Default user with superuser powers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: m4h
      #Directory with the db information
      #- PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
  #adminer:
  #  image: adminer:4.3
  #  ports:
  #      - 5151:8080